### ISSUE TITLE
Inconsistent Documentation!!

### ISSUE THREAD

**Issue by yashksaini-coder** [deepanshu414/SecureCrypt#1]
Hi @deepanshu414 I looked at your `SecureCrypt` and is really amazed by its simplicity and ease of use. However I came to know that the Documentation of the repository is not really convenient for other DEVs. 

If it is okay with you I'd like to Contribute to your repo and make it look more professional. 

Changes I'm planning to do:-
- [x] Add Proper detailed guides with points.
- [x] Explaining Each functions with an example code.
- [ ] Add Images & Video guides for better understanding.
- [x] Writing better markdown to aid in visual steps.

I want to be assigned with this issue. Thank you for you time.

Your Friendly DEV
@yashksaini-coder

**Comment by SamarAanand** [comment]
Hi @deepanshu414 I saw the `good first issue` label and although it is not initialized by you. Your documentation and code can use some modifications. Here's a short introduction of me:-

Full name : Samar Aanand
GitHub Profile Link : https://github.com/SamarAanand
Approach for this Project : 1) Create README Documentation 2) Display Badges 3) Refactor the code 4) Bug fixes 5) Error resolving
Also for your information I am also a GSSoC Contributor with 3 PRs merged.

**Comment by SamarAanand** [comment]
Hi @deepanshu414 I saw the `good first issue` label and although it is not initialized by you. Your documentation and code can use some modifications. Here's a short introduction of me:-

Full name : Samar Aanand
GitHub Profile Link : https://github.com/SamarAanand
Approach for this Project : 1) Create README Documentation 2) Display Badges 3) Refactor the code 4) Bug fixes 5) Error resolving
Also for your information I am also a GSSoC Contributor with 3 PRs merged.

Since no one is currently assigned to this issue, I would like to contribute. 
Do let me know.

**Comment by deepanshu414** [comment]
@yashksaini-coder This is assigned to you
